name: Build and Push to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to GHCR using secrets
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_TOKEN }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 4️⃣ Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_TOKEN }}/nextjs-app:latest
            ghcr.io/${{ secrets.GHCR_TOKEN }}/nextjs-app:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

